GEMINI_API_KEY = "AIzaSyDTAhD09CTTwachULLXzkA33CqFr_qdQgI"

[gcp_service_account]
type = "service_account"
project_id = "ai-training-demo-1-482218"
private_key_id = "36bced8940bfc82ca64c6c43d10d75c22727ca0c"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCvkkpMjJ/ujYLa
mVM5FROpTyKutzSPa9siHkWcHCO+hPgUFTr5If5wNVkP+hrQ0kAKth7vLFkI7gzV
m7uz1MtEtw+ozvxacb9fVNV+ghvm0eC4VDuFIvsYZmbG0LVRZwRl21de8RHcSnVP
mqGFx6zDGZ58PpIDof07kz/6EZwJbOOri6JxrPFMIMhdfNiRhBQ4gNxZxNsHc7ge
mPm/HH5+ggm1uol3w0KCm+RRLXGfuunoFLOmgsgcL8hZg2xDqRgcjplDyDivlaOe
NwjA/AdEX5eah5y5LRfLn7uUEQqYZXcuSoP1VIdylKNkymZWundWzbi4YXi1NxKp
KobmpsxHAgMBAAECggEADATMA0YpI0UarROL5+odHhz7DHzMI06d1029NCeU/CjR
bAaGsqFKGqz8O3oX4IL+u/z69yJ7tynHRSQpCvFz4htUqMNVRm0STa4FWL4Ct6AB
wyc4/9naLdxssrV82WVfnrK6M2ygmApHfOXiosF9fnRALinWXbChdjTpT0QUq2xk
f/IT0WYjLyPDccGpWGD3F37jbkS8L92qF0wevYL1d9vecWiU0sIp2uGIoQG2Ctt0
8Ecw7wDq3fH0zj+O+rNTJjyZLf0dEJE/8BxQKCck5jv88V74J0dcSV23QacRO4Sc
qkuTpds+EPcTCpL0FeTGRrMZQnpwsfb2KozqaUvGCQKBgQD1OF4f+zBhr/vhZswT
ybeYCeBq8Dup82IV+0GOtz9PkRVYFLruAyKjDxDcFA0yjDjxASD51yev3HdDcpha
ytHrFaP2LZCbx0Ppj4y/CpXMRsRlVOIRP+Mbl60t9k96vPPJFrAbIeq4TUBtFb8P
GPy8c9DmI4VbjjTG1K31pZuO9QKBgQC3Sh37sVu3iaPVDfJiZyffMl/8aCNPSXzR
T8fnj7oq1FEnVRXZKJB1UWDywKdnpyzY3gr+v7+R0Xe60Go6VTKFoa8AmORWTT6L
SKUjF8SvNGlQXIO77KiP4F7IndUtynyHyizL15DrkekHq8VJsCinpg/TnRzoWMSM
Jd8ij3SwywKBgQDlJVRHfFmcn2+3FHFVeGTYbTpJk82dJXKd6dk7/J7rwj54vX5k
VYezaauujAo9Fu1KwGxJKzXJzzGfVGFsTiTVEbbSn4eHGjCq+1phVwneBq8VpblO
ty2JJjZNQeLJZfJFEa9k20/UA1RV20FbYVUi4PLva3f9syg8OJeKecOgVQKBgGaV
jQJ52aN33cI49BgvNBmv0BktD9YogzuDM5de0gt2mZUyAfBwy6ldyq0TNp7E6kzW
ucCrAUVTv3dHfqz3UjeIrrHe4K2MvhympAZoHyUQaIEZxoE/i3g7U9FkxRPD6L73
YOsV036FQ6+Pa/Q6LAbo4qLFpJBGXnsyFxj4wY7RAoGBAJaZY7qlCamL+yfYRIH+
nS2iyczJ9+MYKHCMuXxLWtEJlkmo+xPM3FklzhD4Fwhoi9lIGMM7+OmkIxFyNDRM
VtRSKfkns1Ph3u2sZtDiq32PPu9KPjBzQrbd+sYX+QF1lyMKFE9IwUbxCsPelWAu
L3eQtulpTLBsQPb6CeY1+QU7
-----END PRIVATE KEY-----"""
client_email = "uge-engine-manager@ai-training-demo-1-482218.iam.gserviceaccount.com"
client_id = "110904675327629183417"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/uge-engine-manager%40ai-training-demo-1-482218.iam.gserviceaccount.com"
universe_domain = "googleapis.com"

[gcp_service_account_firestore]
type = "service_account"
project_id = "ai-training-demo-1-482218"
private_key_id = "478970b24173ed9b64c9a46fc0566c8e395d6092"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCYOsgHtGTu0aUu
FdMZuvlDtMKgtaIwobMRjrAkGyH3ZHrooHkxwbwvz5Ns+AnjQFPZFehUX+ctpcdK
MOcjhweA/1dRpFJEz5RWrGpXKsJfc8oxiQ9gaExKLnYImphqbGuRpkGNC8lDojve
Fn0salTdY2fJu0GtqmN+lkHNv9+1qv9adqn7qP5Ot+CzGJo01zr2Rxmf8DJNh6Pg
iSz/HmUKqRoFdZsZO/VGLpSyV6mNcoTF06ytOdSlnVOqkBZldYs/dGIKx/1k6Dvn
URXdHPTH+r10rbqWZPYJXBJjl457BIkHfsFpx6/5YYWq6d2WSjk1t/OqrACKUQuU
Urr/7mbTAgMBAAECggEABAu4bD1U0pfqHoAAUrZwx/c+HrHHO6A+8O4U/M8Ry7ro
R96G46cC6UTqmObE9ueAmWFvkshb/KBJ/lWNY907FA6w9aPyZg7oiFIbnyRxe20W
WTmt3goqx9MiOCP8feH9c1oD++ltpTprV19lCYZBQ78DBPjQ+s+ztU2HFECxx+As
Sa6eo07lauTT/AGosdRRM5NCvJBtkxGr+A8gGjS+e5hk69lRVDfBOARxXJ/BTWiz
5w6sX3337MI/drZDEKOV0zWM9A3FoR5bT2ZzOQW0dMA63KE5cabQkeKbcWKPbcdr
j52OfcG9UejwMaJDLHSx2djxyDMhdz2cVQhUAkLJdQKBgQDLq7g3BIe77K0B7MZ7
eY3NqYoj/9DEUC3n5cI/AciK4tBpnwq2FBYzusgrL7nH5KvCPMVA1gQQonMZRPsW
aogwnkGacrkd7NnCU8DTnFR8hBCcj3a/OpxNFMivuAlV7jXJGOHA+jvjwXD91O/9
u1W1rbz5ixtZWDL0xClzOOwLxwKBgQC/V4+Ue1r7t8H8xweaOTrXn8prvNPls/kD
R1LZCmyYmRiDkNCTojRvBVuJ9TZdz7H5wrWQbaocP6KobgoL0Q0F6a+qs9fGDZfc
LhJhFomra3uejpfkiBa9rJ05T9ig5yl5DzDOT0PvJxKedHBJuGVIk8sJ3ixK1ulu
YXV95WAUlQKBgQCW+4KBTptspWQPhD4TNKX5axBb5X0WurV9LmbUHHdU9hU3502i
cruOt41B7oxTceIeCLzVdpHm3vZiKi/Uiz7Qg9DwNNGkLHu1Qi8077P15lUGKpgF
5OYPgjPPh6dsCz3WCNr6Gsag7TrdAKi0ONat6tCnUQcCMY78whpUL0NU6wKBgEAb
0EmJgxRvnxlYfh2YKzTvnty2KbD+ueH1VbbOnVALi4EZVikA4dyIyQDSHeMUoabz
K+42MBbC43bXV5pZ8qkWgPsKwrLi/wyQiyvoZzv+CS84y3+QcT4fxZXcQNK4YNbk
1g9p03MffkeE79Jja9wDWLX3sJNqqk+Ha9xArA55AoGAZxWGeX02/K2o8RayqqS+
vYwhOAEplB2houN5QByPkJECtu/auuAOHSIvJLE8uks4lP7l1E7FtxjgCyZov/5A
tZiHRixWz3hNZ+8KhcY9K9U+nIjZT4rIzauu/RCNjk/yMyIimtYDvmrxbV/jh7lz
fU/ZgOJl2XQ2AIGYMFfEnT0=
-----END PRIVATE KEY-----
"""
client_email = "ule-dataxfer-agent@ai-training-demo-1-482218.iam.gserviceaccount.com"
client_id = "113049205191516126756"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/ule-dataxfer-agent%40ai-training-demo-1-482218.iam.gserviceaccount.com"
universe_domain = "googleapis.com"
